export const LOAD_GAME_STATE = "LOAD_GAME_STATE";
export const SET_INTERACTIVE_PARAMS = "SET_INTERACTIVE_PARAMS";
export const START_RACE = "START_RACE";
export const COMPLETE_RACE = "COMPLETE_RACE";
export const CANCEL_RACE = "CANCEL_RACE";
export const SCREEN_MANAGER = {
  SHOW_HOME_SCREEN: "SHOW_HOME_SCREEN",
  SHOW_ON_YOUR_MARK_SCREEN: "SHOW_ON_YOUR_MARK_SCREEN",
  SHOW_RACE_IN_PROGRESS_SCREEN: "SHOW_RACE_IN_PROGRESS_SCREEN",
  SHOW_RACE_COMPLETED_SCREEN: "SHOW_RACE_COMPLETED_SCREEN",
};
